<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAi31zYO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAi31zYO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAi31zYO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAi31zYO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAi31zYO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ai31zYO',
    'container.build_id' => 'e76f7c31',
    'container.build_time' => 1645659085,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAi31zYO');
